### PR TITLE
Periodically heartbeat GitHub App installations to avoid idle rate-limit demotion

### PR DESCRIPTION
**Pull request by iul1an**
## Summary

- Background goroutine pings each GitHub App installation on a configurable interval (`--heartbeat-interval` / `HEARTBEAT_INTERVAL`, default `10m`) via `Apps.ListRepos`.
- Keeps GitHub-side authenticated activity registered so installations don't get demoted from the high rate-limit tier when the credential picker hasn't selected them for a stretch.
- Two new counters (`github_app_heartbeat_total` and `github_app_heartbeat_errors_total`) expose heartbeat health per installation.

## Problem

GitHub documents the primary rate-limit tier for an App installation as a function of the installation's org properties — 15,000/hr for Enterprise Cloud orgs, scaling from 5,000 up to 12,500 for standard orgs based on user and repo counts ([docs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2026-03-10#primary-rate-limit-for-github-app-installations)). The docs don't describe activity-based demotion.

In practice we've observed installations that go without authenticated traffic for extended periods dropping to a hard ceiling of 500 requests/hour — well below even the documented 5,000/hr floor for standard orgs. The demotion is not documented by GitHub but is reproducible across distinct App IDs and recovers cleanly once the installation receives authenticated traffic. The mechanism (secondary rate limit, undocumented effective tier, abuse-prevention scaling) isn't disclosed; the symptom is consistent.

This is not a functional failure on its own — a demoted installation still serves requests, just with less headroom. The problem is fleet redundancy. The credential picker (introduced in #41) prefers the App with the most remaining headroom, so when one App is consistently picked, the others sit idle and get demoted. If the chosen App later hits 429 or runs into a transient issue, the picker tries to fall back — only to find the alternatives now have an effective ceiling of 500/hr, far too low to absorb the displaced load. Effective fleet capacity collapses to "whatever the currently-warm installation can do" instead of "sum of all installations".

The picker has no way to recover from this on its own; demoted installations need authenticated activity to come back.

## What changes

- **`internal/clients/heartbeat.go`** (new): background goroutine + per-installation ping loop. Skips installations currently in cooldown. Failures fall through the same `pool.recordResponse` plumbing controller traffic uses — 429s trigger pool cooldowns, transport failures trigger exponential backoff.
- **`cmd/provider/main.go`**: starts the goroutine alongside the existing `CleanupExpiredClients` ticker. New CLI flag `--heartbeat-interval` (or env var `HEARTBEAT_INTERVAL`), default `10m`.
- **`internal/clients/client.go`**: new `AppsClient` interface with one method, `ListRepos`. Same shape as existing service-specific interfaces.
- **`internal/clients/cached_client.go`**: `Client` struct now carries an `Apps` field; new `installationOrg` field on `cachedClientEntry` so heartbeat metrics carry the same `(organization, app_id, app_installation_id)` label tuple as controller-driven traffic. Two new cache helpers (`SnapshotCacheKeys`, `LookupEntry`).
- **`internal/clients/rate_limit_client.go`**: `RateLimitAppsClient` wrapper for consistency with the other service-specific wrappers.
- **`internal/clients/fake/client.go`**: matching `MockAppsClient`.
- **`internal/telemetry/rate_limit.go`**: two new counter vecs.

Heartbeat responses also feed `RecordRateLimitInfo`, so `github_rate_limit_remaining`/`_limit`/`_reset_time` stay fresh for installations the picker hasn't selected recently. Same metric shape as controller-driven updates — no synthetic labels.

## Why `Apps.ListRepos`

Callable with installation tokens, registers as authenticated activity, and cheap with `PerPage=1`.

## Test plan

- [x] Unit tests cover happy path, cooldown skip, pool-update on success, and exponential cooldown on transport failure.
- [x] End-to-end verification confirmed each known installation receives one ping per tick, both new counters increment as expected, `github_rate_limit_remaining` refreshes for installations the picker hasn't recently selected, and picker behavior is unchanged.
- [x] `make reviewable` clean.

## Notes

- Cost: one quota point per installation per tick. At the default 10-min interval that's ~6 calls/hr/installation of overhead.
- The heartbeat does not change the credential picker.
- No dependency bumps. No public API changes outside the internal `AppsClient` interface.

### CODE REVIEW

**Comment by iul1an** [comment]
Behavior proof bellow.
image

**Comment by iul1an** [comment]
not needed for now. the issue is just aesthetic and it only affects the order in which credentials are "drained".
